domain = ENV['RUBY_GEMS_CHINA'] ? 'https://gems.ruby-china.com' : 'https://rubygems.org'

source domain

gem "xcode-install"
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
