source "https://gems.ruby-china.com"

gem "xcode-install"
gem "fastlane","2.177.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
